footprint: [ [-0.25,-0.135], [0.25,-0.135], [0.25,0.135], [-0.25,0.135] ]
# car length = 0.50   car width = 0.27
# wheel base = 0.33   track width = 0.23
# front offset = 0.09 rear offset = 0.08
transform_tolerance: 1
obstacle_layer:
  enabled: true
  obstacle_range: 3.0
  raytrace_range: 3.5
  track_unknown_space: false
  combination_method: 1
  observation_sources: lidar
  lidar: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0 # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius: 0.15 # m (max. distance from an obstacle at which costs are incurred for planning paths)
static_layer:
  enabled: true
  map_topic: "/map"
