# GLOBAL PLANNER:
NavfnROS:
  allow_unknown: false # whether or not to allow global planner to create paths that traverse unknown spaces
  default_tolerance: 0.1 # global planner will attempt to plan path that is no further away than this value from the specified goal point
  use_dijkstra: false # if true, use Dijkstra's algorithm, otherwise use A* algorithm

# LOCAL PLANNER:
TebLocalPlannerROS:
  odom_topic: /odom
  map_frame: /map
  # Trajectory
  teb_autosize: True
  dt_ref: 0.4
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 2
  allow_init_backward_motion: false
  # Robot
  # car length = 0.50 m     car width = 0.27 m
  # wheel base = 0.33 m     track width = 0.23 m
  # front offset = 0.09 m   rear offset = 0.08 m
  # max steering angle = 30 deg
  max_vel_x: 0.4 # m/s
  max_vel_x_backwards: 0.2 # m/s
  max_vel_theta: 0.2 # rad/s [angular velocity is also bounded by min_turning_radius in case of a carlike robot (omega = v/r)]
  acc_lim_x: 0.15
  acc_lim_theta: 0.3927
  # Carlike robot parameters
  min_turning_radius: 0.5716 # min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
  wheelbase: 0.33 # wheelbase of the carlike robot
  cmd_angle_instead_rotvel: True # return steering angle instead of the rotvel (angular.z of twist message)
  footprint_model:
    type: "line"
    line_start: [-0.18, 0.0] # for type "line"
    line_end: [0.17, 0.0] # for type "line"
  # GoalTolerance
  xy_goal_tolerance: 0.1 # m
  yaw_goal_tolerance: 0.4 # rad
  free_goal_vel: False
  # Obstacles
  min_obstacle_dist: 0.2 # this value must also include our robot's expansion, since footprint_model is set to "line".
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  # Optimization
  no_inner_iterations: 3
  no_outer_iterations: 3
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1000
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10
  # Homotopy Class Planner
  enable_homotopy_class_planning: False
  enable_multithreading: False
  simple_exploration: False
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False
